# Site settings
title: 旭日东升
SEOTitle: 猛虎就是不一样
header-img: img/post-bg-desk.jpg
email: 2796715822@qq.com
description: "学习，学习，学习"
keyword:" 学习魂"
url: "https://sixuxf66.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/sixuxf66/sixuxf66.github.io.git" # you code repository


# although redcarpet can auto high# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you're going to be!"
sidebar-avatar: /img/about-someone.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



